import { Provider } from "react-redux";
import store from "@/store";
import { Outfit } from "next/font/google";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainProvider from "@/providers/MainProvider";

const outfit = Outfit({
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MainProvider>
      <html lang="en">
        <body className={`bg-[#05051F] ${outfit.className} dark:bg-gray-900`}>
          {children}
        </body>
      </html>
    </MainProvider>
  );
}
